# Generated by Django 3.0.3 on 2020-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret_field',
            field=models.BooleanField(default=False),
        ),
    ]
