# Generated by Django 3.0.3 on 2020-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example2', '0002_auto_20200618_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
