# Generated by Django 3.0.3 on 2020-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example2', '0003_auto_20200618_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='secret_field',
        ),
        migrations.AddField(
            model_name='product',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
