# Generated by Django 3.0.3 on 2020-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example2', '0004_auto_20200618_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
